services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      MONGO_URL: 'mongodb://mongo:27017/social-media'
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
      