name: Deploy Docker to EC2

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY_PATH }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.EC2_INSTANCE_IP }}" >> ~/.ssh/known_hosts

      - name: Build Docker Images
        run: |
          docker-compose build

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
            # Navigate to your app directory
            cd /path/to/your/app  # Change this to your application's path

            # Pull the latest changes
            git pull origin main

            # Install Docker Compose if not installed
            if ! command -v docker-compose &> /dev/null; then
              sudo apt update
              sudo apt install -y docker-compose
            fi

            # Remove old containers if they exist
            docker-compose down || true

            # Run the new containers
            docker-compose up -d
          EOF
