name: CI/CD to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Decode EC2 Key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 --decode > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Deploy to EC2
        env:
          EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}  # Ensure you have this secret set
        run: |
          scp -i ec2-key.pem -o StrictHostKeyChecking=no -r ./* ec2-user@$EC2_INSTANCE_IP:/path/to/deploy
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@$EC2_INSTANCE_IP 'cd /path/to/deploy && npm install && pm2 start your-app.js'

      - name: Clean up
        run: rm ec2-key.pem  # Remove the key file for security
