name: CI/CD to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Build the Docker image locally
      - name: Build Docker image
        run: |
          docker build -t social-media-app .

      # Save the Docker image to a file
      - name: Save Docker image
        run: |
          docker save social-media-app > social-media-app.tar

      # Prepare the EC2 instance
      - name: Prepare EC2 Instance
        env:
          EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}
        run: |
          echo "Preparing EC2 instance at $EC2_INSTANCE_IP"
          ssh -i social-media-node.pem -o StrictHostKeyChecking=no ec2-user@$EC2_INSTANCE_IP 'sudo yum update -y && sudo yum install -y docker && sudo service docker start'

      # Transfer Docker image file to EC2 instance
      - name: Transfer Docker Image to EC2
        env:
          EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}
        run: |
          echo "Transferring Docker image to EC2 instance at $EC2_INSTA
