name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.EC2_KEY_PATH }}" > ~/.ssh/id_rsa  # Save private key to id_rsa
          chmod 600 ~/.ssh/id_rsa  # Secure permissions for the SSH key
          ssh-keyscan -H ${{ secrets.EC2_INSTANCE_IP }} >> ~/.ssh/known_hosts  # Add EC2 instance to known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
            # Install Git if not already installed
            if ! command -v git &> /dev/null; then
              sudo dnf install -y git  # Use dnf for Amazon Linux 2023
            fi

            # Navigate to app directory (make sure to replace this with the correct path)
            cd /path/to/your/app
            
            # Pull latest changes from the repository
            git pull origin main
            
            # Install Docker Compose if not already installed
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            
            # Build Docker images
            docker-compose build
            
            # Stop and remove old containers
            docker-compose down
            
            # Start the new containers in detached mode
            docker-compose up -d
          EOF
